### ISSUE TITLE
Ucapan Terima Kasih dan Sedikit Saran

### ISSUE THREAD

**Issue by jefrydco** [anhzf/Code-Highlighter#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Alwan. Mas juga sudah menambahkan Quasar sebagai kerangka kerja antar mukanya. Di bagian _Highlighted Lines_ juga Mas menambahkan Opsional di bagian labelnya. Luar biasa Mas!

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni

1. Setelah Pengguna Menyimpan Kode, Bagian _Collections_ Tidak Secara Langsung Termuat Ulang Datanya

![Vue.js Intermediate - jefrydco](https://user-images.githubusercontent.com/20434351/96695705-24f4dc00-13b4-11eb-82a1-31ba523a0ca7.gif)

2. Input Highlighted Line Tidak Bisa Berupa Range

Kalau dari API nya kita bisa input _highlighted line_ berupa range, seperti `3-5`. Kita juga bisa input _multiple highlighted line_, seperti `3-5,11-13`.

Semangat selalu ya! :muscle:

**Comment by anhzf** [comment]
siap mas terimakasih masukannya, untuk collections saya terkendala dengan
konsep reactivity saya yang belum kuat. awalnya saya menggunakan push tapi
sepertinya tidak dirender lagi oleh Vue, sehingga saya hapus fitur tersebut. Input highlighted range tidak bisa
karena sejujurnya aku nggak ngecek API dan kebetulan nggak coba2 pake fitur
highlight 😂😂

**Comment by jefrydco** [comment]
Terima kasih kembali Mas.

> untuk collections saya terkendala dengan konsep reactivity saya yang belum kuat. awalnya saya menggunakan push tapi sepertinya tidak dirender lagi oleh Vue

Ahh iya tadi saya sempat cek cek ada bagian yang menggunakan push, tapi untuk fitur hapus nya sepertinya collectionnya termuat kembali Mas.

> Input highlighted range tidak bisa karena sejujurnya aku nggak ngecek API dan kebetulan nggak coba2 pake fitur highlight
Wah iya gapapa Mas. :smile: 

Oiya, nanti kalau Mas ada waktu dan berkenan untuk memperbaiki hal tersebut, Mas bisa menutup isu ini ya. Semangat selalu ya! :muscle:

**Comment by anhzf** [comment]
> Terima kasih kembali Mas.
> 
> > untuk collections saya terkendala dengan konsep reactivity saya yang belum kuat. awalnya saya menggunakan push tapi sepertinya tidak dirender lagi oleh Vue
> 
> Ahh iya tadi saya sempat cek cek ada bagian yang menggunakan push, tapi untuk fitur hapus nya sepertinya collectionnya termuat kembali Mas.
> 
> > Input highlighted range tidak bisa karena sejujurnya aku nggak ngecek API dan kebetulan nggak coba2 pake fitur highlight
> > Wah iya gapapa Mas. 😄
> 
> Oiya, nanti kalau Mas ada waktu dan berkenan untuk memperbaiki hal tersebut, Mas bisa menutup isu ini ya. Semangat selalu ya! 💪

siap terimakasih
